SELECT 
	P.NUMERO_PROJETO
    , P.NUMERO_DEPARTAMENTO
    , F.ULTIMO_NOME
    , F.ENDERECO
    , F.DATA_NASCIMENTO
FROM TB_PROJETO P
INNER JOIN TB_DEPARTAMENTO D ON D.NUMERO_DEPARTAMENTO = P.NUMERO_DEPARTAMENTO
INNER JOIN TB_FUNCIONARIO F ON F.CPF = D.CPF_GERENTE
WHERE  P.LOCAL_PROJETO = 'Mauá'
