SELECT DISTINCT F.PRIMEIRO_NOME, F.NOME_MEIO, F.ULTIMO_NOME
FROM TB_FUNCIONARIO F
INNER JOIN TB_DEPARTAMENTO D ON D.CPF_GERENTE = F.CPF
INNER JOIN TB_DEPENDENTE DE ON DE.CPF_FUNCIONARIO = F.CPF;

SELECT F.PRIMEIRO_NOME, F.NOME_MEIO, F.ULTIMO_NOME
FROM TB_FUNCIONARIO F
INNER JOIN TB_DEPARTAMENTO D ON D.CPF_GERENTE = F.CPF
WHERE F.CPF IN (SELECT CPF_FUNCIONARIO FROM TB_DEPENDENTE)
