SELECT P.NUMERO_PROJETO
FROM TB_PROJETO P
INNER JOIN TB_TRABALHA_EM TE ON TE.NUMERO_PROJETO = P.NUMERO_PROJETO
INNER JOIN TB_FUNCIONARIO F ON F.CPF = TE.CPF_FUNCIONARIO
WHERE  F.ULTIMO_NOME LIKE '%Souza%'
UNION
SELECT P.NUMERO_PROJETO
FROM TB_PROJETO P 
INNER JOIN TB_DEPARTAMENTO D ON D.NUMERO_DEPARTAMENTO = P.NUMERO_DEPARTAMENTO
INNER JOIN TB_FUNCIONARIO F ON F.CPF = D.CPF_GERENTE
WHERE F.ULTIMO_NOME LIKE '%Souza%'
