version: '3'

services:
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "7001:5432"
    environment:
      - POSTGRES_PASSWORD=gerade
    networks: 
      - postgres-network
  
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=fghinzelli@gmail.rs.gov.br
      - PGADMIN_DEFAULT_PASSWORD=sys@dmin!
    ports: 
      - "7002:80"
    depends_on: 
      - postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge
