# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_perfil_campo_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='campo_teste',
        ),
    ]
